# Maven package Java project Web App to Linux on Azure
# Build your Java project and deploy it to Azure as a Linux web app
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main
parameters:
- name: aks
  displayName: Trigger AKS Pipeline
  type: boolean
- name: adf
  displayName: Trigger ADF Pipeline
  type: boolean
- name: servicebus
  displayName: Trigger ServiceBus Pipeline
  type: boolean
- name: signalr
  displayName: Trigger SignalR Pipeline
  type: boolean
- name: postgresql
  displayName: Trigger PostgresSQL Pipeline
  type: boolean
- name: cdn-profile
  displayName: Trigger CDN-Profile Pipeline
  type: boolean
- name: appconfig
  displayName: Trigger AppConfig Pipeline
  type: boolean
- name: cosmos
  displayName: Trigger Cosmos Pipeline
  type: boolean
- name: apim
  displayName: Trigger APIM Pipeline
  type: boolean
- name: app-insights
  displayName: Trigger AppInsights Pipeline
  type: boolean
variables:

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

resources:
  containers:
  - container: u16
    image: ubuntu:16.04

  - container: u18
    image: ubuntu:18.04

  - container: u20
    image: maven

stages:
- ${{ each parameter in parameters }}:
  - stage: ${{ parameter }}

- stage: aks
  jobs:
  - job: MavenPackageAndPublishArtifacts
    displayName: Maven Package and Publish Artifacts
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: Maven@3
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'pom.xml'

    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/*.?(war|jar)'
        TargetFolder: $(Build.ArtifactStagingDirectory)

    - upload: $(Build.ArtifactStagingDirectory)
      artifact: drop

- stage: adf
  dependsOn: []
  jobs:
  - job: B1
    steps:
    - bash: echo "B1"
  - job: B2
    steps:
    - bash: echo "B2"

- stage: apim
  dependsOn: []
  jobs:
  - job: A1
    steps:
    - bash: echo "A1"
  - job: A2
    steps:
    - bash: echo "A2"

- stage: postgre
  dependsOn: []
  jobs:
  - job: RunInContainer
    pool:
      vmImage: $(vmImageName)
    strategy:
      matrix:
        ubuntu20:
          containerResource: u20
    container: $[ variables['containerResource'] ]
    steps:
    - script: printenv
    - task: Maven@3
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'pom.xml'
